# Site settings
title: "Prachi Nayak"
email:
description: "Welcome to my personal website"
baseurl: "/"
url: "https://prachi.co.nz" # the base hostname & protocol for your site

twitter_username:
github_username: PrachiNayakCS

# Build settings
markdown: kramdown
